function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "untitled"};
	this.sidHashMap["untitled"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "untitled:16"};
	this.sidHashMap["untitled:16"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "untitled:19"};
	this.sidHashMap["untitled:19"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Divide"] = {sid: "untitled:14"};
	this.sidHashMap["untitled:14"] = {rtwname: "<Root>/Divide"};
	this.rtwnameHashMap["<Root>/From"] = {sid: "untitled:6"};
	this.sidHashMap["untitled:6"] = {rtwname: "<Root>/From"};
	this.rtwnameHashMap["<Root>/From1"] = {sid: "untitled:7"};
	this.sidHashMap["untitled:7"] = {rtwname: "<Root>/From1"};
	this.rtwnameHashMap["<Root>/From2"] = {sid: "untitled:12"};
	this.sidHashMap["untitled:12"] = {rtwname: "<Root>/From2"};
	this.rtwnameHashMap["<Root>/From3"] = {sid: "untitled:17"};
	this.sidHashMap["untitled:17"] = {rtwname: "<Root>/From3"};
	this.rtwnameHashMap["<Root>/Goto"] = {sid: "untitled:5"};
	this.sidHashMap["untitled:5"] = {rtwname: "<Root>/Goto"};
	this.rtwnameHashMap["<Root>/MATLAB Function"] = {sid: "untitled:16"};
	this.sidHashMap["untitled:16"] = {rtwname: "<Root>/MATLAB Function"};
	this.rtwnameHashMap["<Root>/Max"] = {sid: "untitled:2"};
	this.sidHashMap["untitled:2"] = {rtwname: "<Root>/Max"};
	this.rtwnameHashMap["<Root>/Min"] = {sid: "untitled:4"};
	this.sidHashMap["untitled:4"] = {rtwname: "<Root>/Min"};
	this.rtwnameHashMap["<Root>/Sum of Elements"] = {sid: "untitled:11"};
	this.sidHashMap["untitled:11"] = {rtwname: "<Root>/Sum of Elements"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "untitled:20"};
	this.sidHashMap["untitled:20"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "untitled:21"};
	this.sidHashMap["untitled:21"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "untitled:22"};
	this.sidHashMap["untitled:22"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<Root>/Output3"] = {sid: "untitled:23"};
	this.sidHashMap["untitled:23"] = {rtwname: "<Root>/Output3"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "untitled:16:1"};
	this.sidHashMap["untitled:16:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:1:3"] = {sid: "untitled:16:1:3"};
	this.sidHashMap["untitled:16:1:3"] = {rtwname: "<S1>:1:3"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
